"""final

Revision ID: 80be1808f266
Revises: c9c724b352b8
Create Date: 2025-09-17 15:11:06.698608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80be1808f266'
down_revision = 'c9c724b352b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
